---
exclude_paths:
  - '**/node_modules/**'
  - '**/__mocks__/**'
  - '**/__stubs__/**'
  - '**/__fixtures__/**'
  - '**/__tests__/**'
  - '**/*.spec.ts'
  - '**/*.e2e-spec.ts'
  - '.devcontainer/**'
  - '.github/**'
  - 'scripts/**'
  - '.husky/**'
  - '.vscode/**'
  - 'docker/**'
