name: ci-pr-test

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Linting
        run: pnpm lint:all
      - name: Unit tests
        run: pnpm test:ci
      - name: Smoke test
        run: pnpm smoke
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo $PR_NUM > ./pr_num.txt
      - name: Upload test-results artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            pr_num.txt
            junit.xml
            coverage/lcov.info
            coverage/coverage-final.json
