name: coverage-report
on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: test-results
      - name: Unzip the artifacts
        run: unzip test-results.zip
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/coverage-final.json
