name: test-report
on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JEST Tests
          path: 'junit.xml'
          reporter: jest-junit
      - run: unzip test-results.zip
      - uses: ArtiomTr/jest-coverage-report-action@v2.0.5
        with:
          skip-step: all
          annotations: coverage
          coverage-file: ./coverage/coverage-final.json
          base-coverage-file: ./coverage/coverage-final.json
